export OTA_PACKAGE_SIGNING_KEY=build_env/keys/platform
export DEFAULT_SYSTEM_DEV_CERTIFICATE=build_env/keys/releasekey
export PRODUCT_DEFAULT_DEV_CERTIFICATE=build_env/keys/releasekey
export OTA_PACKAGE_SIGNING_DIR=build_env/keys
